### ISSUE TITLE
Update Pathlib2 rather than a seprate module

### ISSUE THREAD

**Issue by drts01** [zeehio/backports-pathlib-relative-to#1]
Hi. Thank you for your work. Would you consider making a PR to [Pathlib2](https://github.com/jazzband/pathlib2) to add the new functionality?

https://github.com/jazzband/pathlib2/blob/develop/src/pathlib2/__init__.py#L730

**Comment by zeehio** [comment]
Hi,

Thanks for your interest.

Since:
- There are several alternatives (such as pathlib2) better positioned to maintain this package
- This package has a very too narrow scope
- This package has never left the beta state
- There are no known users of this package
- And to be honest, I don't have time to properly maintain this package

I have decided to withdraw the package from pypi and archive this repository.

I would like to submit a pull request to pathlib2, if I find the time to do it. But I can not commit to do that right now.

Thanks for getting in touch!
